name: customers
description: A new Flutter application.

version: 1.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  flare_flutter: 2.0.2
  overlay_support: 1.0.3
  intl_phone_number_input: ^0.7.0+2
  permission_handler: ^6.0.1+1
  responsive_widgets: ^2.0.1
  intro_slider: ^2.2.8
  cupertino_icons: ^1.0.3
  flutter_statusbarcolor: ^0.2.2
  pinput: ^0.1.10
  carousel_slider: ^3.0.0
  webview_flutter: ^2.3.0
  flutter_rating: ^0.0.2
  grouped_buttons: ^1.0.4
  google_maps_flutter: ^2.0.1
  dio: ^4.0.0
  cached_network_image: ^3.1.0
  rflutter_alert: ^1.0.2
  loading_indicator: "^1.0.0"
  flutter_spinkit: "^4.0.0"
  file_picker: ^1.3.8
  image_picker: ^0.6.1
  fluttertoast: ^4.0.1
  dropdown_menu: ^1.1.1
  shared_preferences: ^2.0.0
  flutter_svg: ^0.22.0
  place_picker: ^0.9.19
  datetime_picker_formfield: any
  geocoder: ^0.2.1
  pedantic: ^1.9.0
  firebase_auth: ^3.3.8
  firebase_messaging: ^10.0.5
  firebase_storage: ^10.0.0
  cloud_firestore: ^3.1.9
  photo_view: ^0.5.0
  page_view_indicators: ^1.3.1
  progress_dialog: ^1.1.0+1
  flutter_html: ^2.1.1
  flutter_share: ^1.0.2+1
  location: ^4.1.1
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.0.9
  easy_localization: ^3.0.0
  showcaseview: ^0.1.5
  connectivity_wrapper: ^1.0.6
  provider: ^5.0.0
  community_material_icon: ^5.4.55
  google_maps_place_picker: ^2.0.0-nullsafety.1
  # story_view: 0.13.1
  firebase_dynamic_links: ^2.0.8
  package_info: 0.4.3
  launch_review: 2.0.0
  auto_size_text: ^2.1.0
  flutter_parsed_text: ^1.2.5
  flutter_gifimage: ^1.0.1
  fl_chart: ^0.36.4
  charts_flutter: ^0.10.0
  video_player: ^2.1.14
  http: ^0.13.3
  flutter_local_notifications: ^5.0.0
  better_player: ^0.0.73
  video_thumbnail: ^0.4.3
  flutter_cache_manager: ^3.1.2
  flutter_math_fork: ^0.3.3+1
  flutter_inappwebview: ^5.3.2
  device_preview: ^1.0.0
  # flutter_google_places: ^0.3.0
  # google_api_headers: ^1.5.0+1
  places_service: ^0.1.0
  google_api_headers: ^1.0.0
  google_maps_webservice: ^0.0.19
  # geocoding: ^2.0.0
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^3.1.3
  pin_input_text_field: ^4.4.1
  # firebase_messaging: ^11.2.7
  firebase_core_platform_interface: 4.2.4
  # firebase_messaging: ^13.0.4
  # firebase_messaging: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_local_notifications:
  #   path: ./flutter_local_notifications-590d8190ef76f5c32c0fc16 ffcb21c4443decf33
  flutter_launcher_icons: ^0.9.0

dependency_overrides:
  flutter_math_fork: ^0.4.0
  provider: ^6.0.0
  charts_flutter: ^0.12.0
  platform: ^3.1.0
  visibility_detector: ^0.2.2
  firebase_messaging_platform_interface: 3.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/logodex.png"
  image_path_ios: "assets/images/logodex.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - translations/
    - assets/flrs/
    - assets/images/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JF-Flat
      fonts:
        - asset: fonts/JF-Flat-Regular.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/JF-Flat-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
